namespace ShadowPluginLoader.MetaAttributes;

/// <summary>
/// Represents properties that specify aliases for classes generated by enumerated types.
/// </summary>
[AttributeUsage(AttributeTargets.Enum)]
public class ShadowSettingClassAttribute : Attribute
{
    /// <summary>
    /// Plugin Alias
    /// </summary>
    public string Alias { get; }

    /// <summary>
    /// Setting Container
    /// </summary>
    public string Container { get; }

    /// <summary>
    /// Represents properties that specify aliases for classes generated by enumerated types
    /// </summary>
    public ShadowSettingClassAttribute(string container, string alias)
    {
        Alias = alias;
        Container = container;
    }
}