namespace ShadowPluginLoader.MetaAttributes;

/// <summary>
/// Represents properties that specify aliases for classes generated by enumerated types.
/// </summary>
/// <example>
/// <code>
/// [ShadowPluginSettingClass(typeof(EmojiPlugin), "Setting")]
/// [ShadowSettingClass("ShadowExample.Plugin.Emoji","EmojiSetting")]
/// public enum BikaConfigKey
/// {
///     [ShadowSetting(typeof(int), "1", "Api分流")]
///     ApiShunt,
///
///     [ShadowSetting(typeof(bool), "true", "登陆后记住我")]
///     RememberMe,
///
///     [ShadowSetting(typeof(string), "tt",comment: "测试名称")]
///     TestName,
///
///     [ShadowSetting(typeof(string), "Temp",  "测试名称", true)]
///     TempPath,
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Enum)]
public class ShadowSettingClassAttribute : Attribute
{
    /// <summary>
    /// Plugin Alias
    /// </summary>
    public string Alias { get; }

    /// <summary>
    /// Setting Container
    /// </summary>
    public string Container { get; }

    /// <summary>
    /// Represents properties that specify aliases for classes generated by enumerated types
    /// </summary>
    public ShadowSettingClassAttribute(string container, string alias)
    {
        Alias = alias;
        Container = container;
    }
}