namespace ShadowPluginLoader.MetaAttributes;

/// <summary>
/// Represents properties that specify aliases for classes generated by enumerated types.
/// </summary>
[AttributeUsage(AttributeTargets.Enum)]
public class ShadowPluginSettingClassAliasAttribute : Attribute
{
    /// <summary>
    /// Plugin Alias
    /// </summary>
    public string Alias { get; init; }

    /// <summary>
    /// Represents properties that specify aliases for classes generated by enumerated types
    /// </summary>
    public ShadowPluginSettingClassAliasAttribute(string alias)
    {
        Alias = alias;
    }
}