name: Publish Nuget Packages

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowPluginLoader.Tool
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      # 缓存 NuGet 包
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.dotnet
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-ShadowPluginLoader.Tool
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            9.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Create NugetPackages
        run: |
          cd ..
          mkdir NugetPackages
          
      - name: Build Packages
        run: |
          dotnet build ShadowPluginLoader.Attributes/ShadowPluginLoader.Attributes.csproj -p:Configuration=Release
          dotnet pack ShadowPluginLoader.Attributes/ShadowPluginLoader.Attributes.csproj -p:Configuration=Release
          dotnet build ShadowPluginLoader.Tool/ShadowPluginLoader.Tool.csproj -p:Configuration=Release
          dotnet pack ShadowPluginLoader.Tool/ShadowPluginLoader.Tool.csproj -p:Configuration=Release
          dotnet build ShadowPluginLoader.VersionGen/ShadowPluginLoader.VersionGen.csproj -p:Configuration=Release
          dotnet pack ShadowPluginLoader.VersionGen/ShadowPluginLoader.VersionGen.csproj -p:Configuration=Release
      
      - name: Push package to Nuget registry
        run: |
          cd ..\NugetPackages
          ls
          dotnet nuget push "*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY --skip-duplicate        
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
