name: Publish Nuget Packages

on:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowPluginLoader.Tool
    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            8.0.x
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Create NugetPackages
        run: |
          mkdir NugetPackages
          
      - name: Build Packages
        run: |
          dotnet restore $env:Solution_Name/$env:Solution_Name.csproj
          dotnet build $env:Solution_Name/$env:Solution_Name.csproj -p:Configuration=Release

      - name: Push package to Nuget registry
        run: |
          dotnet nuget push "NugetPackages\*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY 
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}